version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: care_ai
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=care_ai
      - SECRET_KEY=YOUR_SECRET_KEY_HERE
    depends_on:
      - db

volumes:
  db_data::
