import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Mic, Send, Clock, Thermometer, ArrowRight } from "lucide-react";
import Link from "next/link";
import { api } from "@/lib/api";
import { toast } from "@/hooks/use-toast";

const bodyParts = [
  "Head", "Eyes", "Throat", "Chest", "Abdomen", "Back", "Arms", "Legs", "Skin", "Joints"
];

const suggestedSymptoms = [
  "Headache", "Fever", "Cough", "Fatigue", "Nausea", "Body aches", "Sore throat", "Dizziness"
];

export default function SymptomChecker() {
  const [step, setStep] = useState<"input" | "questions" | "result">("input");
  const [text, setText] = useState("");
  const [selectedParts, setSelectedParts] = useState<string[]>([]);
  const [feverLevel, setFeverLevel] = useState(37.5);
  const [chills, setChills] = useState<0 | 1>(0);
  const [headache, setHeadache] = useState<0 | 1 | 2 | 3>(1);
  const [nausea, setNausea] = useState<0 | 1>(0);
  const [age, setAge] = useState(30);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [diagnosis, setDiagnosis] = useState<{
    diagnosis: string;
    confidence: number;
    doctorAdvice: string;
  } | null>(null);
  const [error, setError] = useState("");

  const analyzeMalaria = async () => {
    setIsAnalyzing(true);
    setError("");

    try {
      const response = await api.post("/malaria/check", {
        fever_level: feverLevel,
        chills,
        headache,
        nausea,
        age,
      });

      setDiagnosis({
        diagnosis: response.data?.diagnosis ?? "Unknown",
        confidence: response.data?.confidence ?? 0,
        doctorAdvice: response.data?.doctor_advice ?? "No advice provided.",
      });
      setStep("result");
      toast({
        title: "Assessment complete",
        description: "Malaria model result is ready.",
      });
    } catch (err: any) {
      const detail = err?.response?.data?.detail;
      const message = typeof detail === "string" ? detail : "Unable to complete diagnosis right now.";
      setError(message);
      toast({
        title: "Assessment failed",
        description: message,
        variant: "destructive",
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  if (step === "result") {
    const confidence = diagnosis ? Math.round(diagnosis.confidence * 100) : 0;
    const severityLabel = confidence >= 70 ? "Moderate Severity" : "Low Severity";

    return (
      <div className="max-w-3xl space-y-6">
        <div>
          <h1 className="font-display text-2xl font-bold mb-1">Diagnosis Result</h1>
          <p className="text-muted-foreground text-sm">Based on your symptoms and health history</p>
        </div>

        {/* Primary Condition */}
        <Card className="border-warning/30 bg-warning/5">
          <CardContent className="p-6">
            <div className="flex items-start justify-between mb-4">
              <div>
                <Badge className="bg-warning/20 text-warning border-warning/30 mb-2">{severityLabel}</Badge>
                <h2 className="font-display text-xl font-bold">{diagnosis?.diagnosis ?? "Unknown"}</h2>
                <p className="text-muted-foreground text-sm mt-1">Generated by the backend malaria model from your input symptoms</p>
              </div>
              <div className="text-right">
                <div className="font-display text-3xl font-bold text-warning">{confidence}%</div>
                <span className="text-xs text-muted-foreground">Confidence</span>
              </div>
            </div>
            <div className="flex gap-2 text-xs text-muted-foreground">
              <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> Real-time API inference</span>
              <span className="flex items-center gap-1"><Thermometer className="h-3 w-3" /> {feverLevel.toFixed(1)} C</span>
            </div>
          </CardContent>
        </Card>

        {/* Action Plan */}
        <Card>
          <CardContent className="p-6">
            <h3 className="font-display font-semibold mb-3">Doctor Advice</h3>
            <p className="text-sm text-muted-foreground">{diagnosis?.doctorAdvice ?? "No advice returned."}</p>
          </CardContent>
        </Card>

        <div className="flex flex-wrap gap-3">
          <Link href="/doctors"><Button variant="hero">Book a Doctor</Button></Link>
          <Link href="/facilities"><Button variant="outline">Find Pharmacy</Button></Link>
          <Button variant="outline" onClick={() => setStep("input")}>Run New Check</Button>
        </div>

        <p className="text-xs text-muted-foreground border-t border-border pt-4">
          ⚠️ This is an AI-assisted assessment and not a medical diagnosis. Always consult a qualified healthcare provider for confirmation and treatment.
        </p>
      </div>
    );
  }

  if (step === "questions") {
    return (
      <div className="max-w-2xl space-y-6">
        <div>
          <h1 className="font-display text-2xl font-bold mb-1">Follow-up Questions</h1>
          <p className="text-muted-foreground text-sm">These inputs are sent directly to the malaria prediction model</p>
        </div>
        <Card>
          <CardContent className="p-4 space-y-4">
            <div>
              <p className="text-sm font-medium mb-2">Body temperature (Celsius)</p>
              <input
                type="number"
                min={35}
                max={42}
                step={0.1}
                value={feverLevel}
                onChange={(e) => setFeverLevel(Number(e.target.value))}
                className="w-full rounded-lg border border-border px-3 py-2 text-sm bg-background"
              />
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Age</p>
              <input
                type="number"
                min={1}
                max={120}
                value={age}
                onChange={(e) => setAge(Number(e.target.value))}
                className="w-full rounded-lg border border-border px-3 py-2 text-sm bg-background"
              />
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Chills</p>
              <div className="flex gap-2">
                <button onClick={() => setChills(1)} className={`px-3 py-1.5 rounded-lg border text-sm ${chills === 1 ? "bg-primary text-primary-foreground border-primary" : "border-border"}`}>Yes</button>
                <button onClick={() => setChills(0)} className={`px-3 py-1.5 rounded-lg border text-sm ${chills === 0 ? "bg-primary text-primary-foreground border-primary" : "border-border"}`}>No</button>
              </div>
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Headache severity (0-3)</p>
              <div className="flex flex-wrap gap-2">
                {[0, 1, 2, 3].map((value) => (
                  <button
                    key={value}
                    onClick={() => setHeadache(value as 0 | 1 | 2 | 3)}
                    className={`px-3 py-1.5 rounded-lg border text-sm ${headache === value ? "bg-primary text-primary-foreground border-primary" : "border-border"}`}
                  >
                    {value}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Nausea</p>
              <div className="flex gap-2">
                <button onClick={() => setNausea(1)} className={`px-3 py-1.5 rounded-lg border text-sm ${nausea === 1 ? "bg-primary text-primary-foreground border-primary" : "border-border"}`}>Yes</button>
                <button onClick={() => setNausea(0)} className={`px-3 py-1.5 rounded-lg border text-sm ${nausea === 0 ? "bg-primary text-primary-foreground border-primary" : "border-border"}`}>No</button>
              </div>
            </div>
          </CardContent>
        </Card>

        {error && (
          <Card className="border-emergency/30 bg-emergency/5">
            <CardContent className="p-4 text-sm text-emergency">{error}</CardContent>
          </Card>
        )}

        <Button variant="hero" onClick={analyzeMalaria} className="w-full h-11" disabled={isAnalyzing}>
          {isAnalyzing ? "Analyzing..." : "Get Diagnosis"} <ArrowRight className="ml-1 h-4 w-4" />
        </Button>
      </div>
    );
  }

  return (
    <div className="max-w-3xl space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold mb-1">Symptom Checker</h1>
        <p className="text-muted-foreground text-sm">Describe your symptoms to get an AI-powered assessment</p>
      </div>

      {/* Text Input */}
      <Card>
        <CardContent className="p-4">
          <Textarea
            value={text}
            onChange={e => setText(e.target.value)}
            placeholder="Describe your symptoms... e.g., I've had a headache and fever for 3 days"
            className="min-h-25 resize-none border-0 p-0 focus-visible:ring-0 text-base"
          />
          <div className="flex items-center justify-between mt-3 pt-3 border-t border-border">
            <Button variant="ghost" size="sm"><Mic className="h-4 w-4 mr-1" /> Voice</Button>
            <Button variant="hero" size="sm" onClick={() => setStep("questions")}>
              <Send className="h-4 w-4 mr-1" /> Analyze
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Quick Symptoms */}
      <div>
        <p className="text-sm font-medium mb-3">Quick Select</p>
        <div className="flex flex-wrap gap-2">
          {suggestedSymptoms.map(s => (
            <button key={s} className="px-3 py-1.5 rounded-lg border border-border text-sm hover:bg-accent hover:border-primary/30 transition-colors">
              {s}
            </button>
          ))}
        </div>
      </div>

      {/* Body Map (simplified) */}
      <Card>
        <CardContent className="p-4">
          <p className="text-sm font-medium mb-3">Select affected area</p>
          <div className="grid grid-cols-5 gap-2">
            {bodyParts.map(part => (
              <button
                key={part}
                onClick={() => setSelectedParts(
                  selectedParts.includes(part) ? selectedParts.filter(p => p !== part) : [...selectedParts, part]
                )}
                className={`py-2.5 rounded-lg border text-sm font-medium transition-all ${
                  selectedParts.includes(part) ? "bg-primary text-primary-foreground border-primary" : "border-border hover:border-primary/30"
                }`}
              >
                {part}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
